name: Cypress Tests with Dependency and Artifact Caching

on:
    push:
    # paths:
    #     - "apps/ui/**"
    #     - ".github/workflow/cypress.yaml"

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        # container: cypress/browsers:node16.13.2-chrome100-ff98
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Download the build folders
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: build

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"

            - name: Install dependencies
              run: yarn

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  build: yarn build
