name: Cypress Tests

on:
    pull_request:
        paths:
            - "apps/ui/**"
            - ".github/workflows/cypress.yml"

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  install: true
                  working-directory: apps/ui
                  # build: yarn build
                  start: yarn dev
                  wait-on: "http://localhost:3000"

            - uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-screenshots
                  path: apps/ui/cypress/screenshots

            - name: Monitor coverage
              uses: slavcodev/coverage-monitor-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  coverage_path: "apps/ui/coverage/clover.xml"
                  comment_footer: false
