name: Cypress Tests

on:
    push:
        paths:
            - "apps/ui/**"
            - ".github/workflows/cypress.yaml"

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        # container: cypress/browsers:node16.13.2-chrome100-ff98
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  install: true
                  working-directory: apps/ui
                  build: yarn build
                  start: yarn preview
                  wait-on: "http://localhost:3000"
