name: Cypress Tests

on:
    push:
        paths:
            - "apps/ui/**"
            - ".github/workflows/cypress.yml"

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  install: true
                  working-directory: apps/ui
                  # build: yarn build
                  start: yarn dev
                  wait-on: "http://localhost:3000"

            - uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-screenshots
                  path: apps/ui/cypress/screenshots

            - name: Generate NYC report
              id: get-comment-body
              working-directory: ./apps/ui
              run: |
                  body=$(npx nyc report --reporter=text-summary)
                  echo ::set-output name=body::$body

            - name: Create commit comment
              uses: peter-evans/commit-comment@v2
              with:
                  body: ${{ steps.get-comment-body.outputs.body }}
